### ISSUE TITLE
Bad display of the speaker info!

### ISSUE THREAD

**Issue by jlandure** [GDG-Nantes/devfest2017#132]
https://devfest.gdgnantes.com/speakers/104

<img width="1254" alt="capture d ecran 2017-06-15 a 14 52 39" src="https://user-images.githubusercontent.com/525974/27182061-4d9bf2c8-51da-11e7-91b9-ede049811875.png">

**Comment by jefBinomed** [comment]
Curieux j'ai pas le soucis... t'es sous quoi comme version de chrome ?

![image](https://user-images.githubusercontent.com/681267/27182336-157f2224-51db-11e7-8379-515e85c7e4a4.png)

**Comment by jlandure** [comment]
Version 59.0.3071.86 (Build officiel) (64 bits)

**Comment by jlandure** [comment]
suffit de changer la hauteur à 500px et c'est moche ^^ (sur mon chrome canary aussi)

**Comment by jefBinomed** [comment]
ok, je regarde ça ce soir

**Comment by jlandure** [comment]
C'est toujours pas terrible ^^
<img width="1154" alt="capture d ecran 2017-06-16 a 11 31 42" src="https://user-images.githubusercontent.com/525974/27221034-6e5adf8a-5287-11e7-921b-e7d4617e72a5.png">

**Comment by jefBinomed** [comment]
ué mais tu peux scroller non ? en fait, je vois pas trop ce qu'on peut faire si la personne met une bio importante....

**Comment by jlandure** [comment]
bah le truc, c'est qu'on a vachement de place et on se retrouve avec une scrollbar ^^
C'est moche non ? (citation de @pguyard)

**Comment by jefBinomed** [comment]
![cest_pas_faux](https://user-images.githubusercontent.com/681267/27221985-e31dd004-528a-11e7-8fa5-7fc7bbd1e578.gif)

faudrait plus mettre @bpetetot dessus du coup 😄

**Comment by jlandure** [comment]
tjs aussi moche chez moi 
https://devfest.gdgnantes.com/speakers/2587/

**Comment by jefBinomed** [comment]
ué va falloir sérieusement se pencher sur ce bug....

**Comment by jefBinomed** [comment]
résolu avec le gros batch de corrections, j'ai juste oublié de référencé la bonne issue. Mais à toi de confirmer qu'on peut fermer le ticket
