### ISSUE TITLE
Enlever docker advocate

### ISSUE THREAD

**Issue by jlandure** [GDG-Nantes/devfest2017#173]
<img width="293" alt="capture d ecran 2017-07-17 a 20 43 37" src="https://user-images.githubusercontent.com/525974/28284277-b1fce596-6b30-11e7-9666-ed2b4cf69cad.png">
T'es sur de ça @jefBinomed ?

**Comment by jefBinomed** [comment]
en effet, il ne l'est pas. j'étais convaincu. je vais donc virer le badge :+1:

**Comment by jlandure** [comment]
puis le sous titre de la capture `Docker Developer Expert` n'existe pas ^^
