### ISSUE TITLE
Meilleure gestion des salles dans l'API mobile

### ISSUE THREAD

**Issue by bpetetot** [GDG-Nantes/devfest2017#214]
**de @cyrilmottier :**
Ton fix (#213) marche dans le cas présent mais si genre le 18 octobre vous apprenez que, exemple, si les speakers X et Y  viennent pas et que vous les remplacez pas, ça va décaler toutes les salles

En gros le système actuel est broken by design
Car il peut pas y avoir un "trou" dans l'agenda
Ça serait pas mieux de faire le travail en utilisant `session.track.title` ?

**Comment by jlandure** [comment]
no need
