### ISSUE TITLE
Les tags pour Hugo Mougard sont faux

### ISSUE THREAD

**Issue by jlandure** [GDG-Nantes/devfest2017#219]
Je pense qu'on a pris les tags pour Guillaume Chau... Je les enlève pour le moment...

**Comment by jlandure** [comment]
je mets juste "Machine Learning" pour le moment

**Comment by jlandure** [comment]
ping @jefBinomed des news sur les tags ?

**Comment by jefBinomed** [comment]
Euh non j'ai pas pris le temps de regarder
