### ISSUE TITLE
ajouter l'offre residhome en solution d'hébergement

### ISSUE THREAD

**Issue by pguyard** [GDG-Nantes/devfest2017#260]
RESIDHOME BERGES DE LA LOIRE NANTES **** 
3 Allée Jacques Berque – 44 000 NANTES
+33 (0)2 40 99 07 07
http://www.residhome.com/
Situé au cœur de Nantes, dans un cadre unique de verdure sur les bords de Loire. A 5 minutes à pied de la gare SNCF, de la navette aéroport et à proximité immédiate de la Cité des Congrès.
Tarif préférentiel pour le DEVFEST 2017
Studio Standard : 95.00 € TTC par nuit en occupation single, double ou twin.
Petit Déjeuner Buffet Américain 11.50 € par personne par jour
Taxe de séjour 2.25 € per personne par jour
Pour bénéficier de ce tarif préférentiel, merci de nous contacter en mentionnant le code « DEVFEST 2017» par mail caroline.dulong@reside-etudes.fr ou corinne.lallemand@reside-etudes.fr.

**Comment by jlandure** [comment]
Humff
L'année dernière :
> 97.50€ la nuit entre le 8 et 10 novembre 2016 (Studio standard single,
incluant petit déjeuner buffet américain)
C'est pas terrible en fait.
