### ISSUE TITLE
Ajouter des vidéos 2016 les plus vues

### ISSUE THREAD

**Issue by bpetetot** [GDG-Nantes/devfest2017#4]
Mettre les vidéos 2016 les plus vues

A mettre dans le fichier `/data/videos.json`

Format : 
```json

{
    "youtubeId": "Jv5LmQOXmjU",
    "title": "Cloud patterns",
    "speakers": "Didier Girard & Julien Landuré",
    "thumbnail": "/images/sessions/dgirard.jpg"
  }

```

⚠️ Ne pas oublier d'ajouter une image pour chaque vidéo dans le dossier `/images/sessions`. Prendre une image de la conf dans le flickr

**Comment by jlandure** [comment]
sniff j'ai perdu ma conf :(

**Comment by xavmarc** [comment]
j'ai pris les vidéos les plus vues désolé :yum:
