### ISSUE TITLE
Se mettre en valeur dans la page "team"

### ISSUE THREAD

**Issue by jlandure** [GDG-Nantes/devfest2017#47]
Je propose d'ajouter notre fonction + société pour se mettre en valeur. Zenika sera toujours content de voir qu'ils sont cités côté orga et que ça justifie les qques jours que j'ai pour le DevFest 👍

On le fait bien dans notre dossier de sponsoring d'ailleurs.

**Comment by xavmarc** [comment]
:+1:

**Comment by xavmarc** [comment]
On mettrait ça à la place de la fonction GDG ?
