### ISSUE TITLE
Revoir la phrase pour les droits à l'image

### ISSUE THREAD

**Issue by jlandure** [GDG-Nantes/devfest2017#48]
`Par votre inscription, vous autorisez le GDG à utiliser et à publier les photos prises lors de l'évènement sans limite de durée.`
On n'indique pas que c'est une photo de la personne donc bon il accepte que des photos soient diffusées mais il indique pas que c'est une photo de lui-même ! 😝
Perso je préfère indiquer cela sur Yurplan plutôt... Qu'en pensez-vous ?

**Comment by xavmarc** [comment]
:+1:

**Comment by pguyard** [comment]
Et il ne faut pas parler que des photos mais aussi des vidéos.

**Comment by pguyard** [comment]
cf: devoxx :  http://reg.devoxx.fr/assets/legal.html

Le Droit à l'image
Lors de votre participation à Devoxx France comme orateur ou conférencier, vous acceptez d'être filmé ou photographié. En tant que conférencier, il est possible que vous soyez pris en photo de groupe ou de foule. Or le droit Français prévoit qu'au delà d'un certain nombre de personnes sur une photo, votre droit à l'image ne peut être invoqué.

En tant qu'orateur, vous acceptez que votre présentation soit filmée et enregistrée. Vous vous engagez à n'utiliser que du contenu libre de droits ou pour lesquels vous aurez fait les achats de licences nécessaires (images, musiques). Vous acceptez que votre présentation soit diffusée gratuitement sur le site Parleys.com.

**Comment by xavmarc** [comment]
**Proposition texte :**
Lors de votre participation au DevFest Nantes comme orateur ou participant, vous acceptez d'être filmé et photographié. En tant que participant, il est possible que vous soyez pris en photo de groupe ou de foule. Or le droit français prévoit qu'au delà d'un certain nombre de personnes sur une photo, votre droit à l'image ne peut être invoqué.
En tant qu'orateur, vous acceptez que votre présentation soit filmée et enregistrée. Vous vous engagez à n'utiliser que du contenu libre de droits ou pour lesquels vous aurez fait les achats de licences nécessaires (images, musiques). Vous acceptez que votre présentation soit diffusée gratuitement sur Youtube.

* *Dans Home on mettrait juste une phrase indiquant d'aller voir les droits à l'image dans la FAQ*
* *Dans FAQ on rajouterait le texte sous la question "Comment s'inscrire et combien cela coûte-t-il ?"*

**Comment by jlandure** [comment]
Pas bon la phrase "or le droit français" ça veut rien dire. 😀

Le mar. 21 févr. 2017 09:06, Xavier MARC <notifications@github.com> a
écrit :

**Comment by xavmarc** [comment]
@jlandure ca te va du coup la phrase ? :yum:
