### ISSUE TITLE
Revoir le blabla pour le tarif réduit pour que ça fasse plus beau

### ISSUE THREAD

**Issue by jlandure** [GDG-Nantes/devfest2017#49]
Diminuer le blabla car ça fait moche... Mettre un lien dans faq pour dire c'est quoi les tarifs réduits ? Ca surcharge trop la page d'accueil.

Pareil, je pense qu'il est inutile d'écrire que le ticket n'inclut pas de logement... C'est évident...

<img width="977" alt="capture d ecran 2017-02-12 a 14 35 24" src="https://cloud.githubusercontent.com/assets/525974/22862539/e97fa55a-f130-11e6-81ff-25b96a01f2a4.png">

**Comment by pguyard** [comment]
:+1: pour le logement

**Comment by pguyard** [comment]
Ces tickets donneNT

**Comment by jlandure** [comment]
déjà prévu 👍  tu verras la PR dans 5 min

**Comment by jlandure** [comment]
#53
