### ISSUE TITLE
FAQ : Revoir les textes

### ISSUE THREAD

**Issue by jefBinomed** [GDG-Nantes/devfest2017#51]
* Comment va se dérouler le DevFest => On parle d'une journée, alors qu'on est sur 2 jours

* Revoir les catégories ?

* Revoir le tarif, on parle pas des early

* ⚠️ On parle de Yurplan => attention à peut être virer ou alors trouver une autre formulation pour faire disparaitre la notion de yurplan

* On dit que le cfp est ouvert alors qu'il ne le sera pas au moment de l'ouverture du site => ⚠️ 

* On devrait peut être rajouter un item sur la notion de CPF pour préciser qu'on en fait pas

**Comment by jlandure** [comment]
remettre #48 dans la FAQ
