### ISSUE TITLE
Préparer un premier article de blog

### ISSUE THREAD

**Issue by bpetetot** [GDG-Nantes/devfest2017#9]
**Sujet :** 
 - Annonce date, lieu
 - Ouverture du site
 - Les premiers top speakers
 - Nous suivre sur twitter

**Procédure pour ajouter un article :**
- Ecrire l'article en markdown dans le dossier `/data/posts`
- Déclarer l'article dans le fichier `/data/blog.js`
- Associer une image à l'article dans `/images/posts`

⚠️ Ne pas oublier de supprimer les anciens articles et images associées

**Comment by xavmarc** [comment]
Est ce qu'on gère la traduction des posts ? Car pour le moment ce n'est pas implémenté.
